name: Check RSS for new content

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "*/10 * * * *"

concurrency:
    group: check-rss

env:
    DEBUG: ${{ secrets.DEBUG || vars.DEBUG }}

jobs:
    check-rss-for-new-content:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4

            - name: Install dependencies and rclone
              run: |
                  pip install -r requirements.txt -q
                  sudo -v ; curl https://rclone.org/install.sh | sudo bash

            - name: Setup environment variables and rclone config
              run: |
                  mkdir -p ~/.config/rclone
                  echo "${{ secrets.RCLONE_CONFIG || vars.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
                  echo "${{ secrets.ENV || vars.env }}" > $GITHUB_WORKSPACE/.env

            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  name: rss-data
                  workflow_conclusion: ""
                  if_no_artifact_found: warn

            - name: Run check script
              timeout-minutes: 120
              run: |
                  python3 -m src

            - name: Upload artifacts
              if: '!cancelled()'
              uses: actions/upload-artifact@v3
              with:
                  name: rss-data
                  path: rss-data.json
