name: Check RSS for new content

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "*/10 * * * *"

concurrency:
    group: check-rss

env:
    RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG || vars.RCLONE_CONFIG }}
    RCLONE_CONFIG_PATH: rclone.conf
    RCLONE_DEST: ${{ secrets.RCLONE_DEST || vars.RCLONE_DEST }}
    RSS_URL: ${{ secrets.RSS_URL || vars.RSS_URL }}
    HTTP_URL: ${{ secrets.HTTP_URL || vars.HTTP_URL }}
    LAST_CHECKED_ON: ${{ secrets.LAST_CHECKED_ON || vars.LAST_CHECKED_ON }}

jobs:
    check-rss-for-new-content:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  cache: "pip"
            - run: pip install -r requirements.txt

            - name: Setup rclone
              id: cache-primes
              uses: actions/cache@v3
              with:
                  path: |
                      /usr/bin/rclone
                      /usr/local/share/man/man1/rclone.1
                  key: ${{ runner.os }}-rclone
            - run: |
                  sudo -v ; curl https://rclone.org/install.sh | sudo bash
                  echo "$RCLONE_CONFIG" > $RCLONE_CONFIG_PATH

            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  name: rss-data
                  github_token: ${{secrets.GITHUB_TOKEN}}
                  workflow_conclusion: success
                  if_no_artifact_found: warn

            - name: Run check script
              timeout-minutes: 330
              run: |
                  python3 main.py

            - name: Upload artifacts
              if: "!cancelled()"
              uses: actions/upload-artifact@v3
              with:
                  name: rss-data
                  path: rss-data.json
